name: Dependency Review - Vulnerability

###
# This workflow analyzes dependencies introduced by pull requests to help identify security vulnerabilities.
#
# To override the default configuration preset, set the `DEPENDENCY_REVIEW_CONFIG_PRESET` variable in the repository settings.
# The default preset is "vulnerability-high". This preset has this behavior:
#
#   Fail if a dependency is found in the dependency tree with a high severity or greater.
###

on:
  merge_group:
  pull_request:

permissions: {}

jobs:
  vulnerability:
    name: Vulnerabilities
    permissions:
      contents: read
    runs-on: ubuntu-latest
    # Skip on merge group events
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Check PR Existence
        id: check-pr-existence
        uses: ./.github/actions/check-pr-existence

      - name: Dependency Review
        # Avoid running this on an initial commit where we assume we're dealing
        # with a repo with no prior PRs.
        if: ${{ steps.check-pr-existence.outputs.has-prs == 'true' }}
        uses: smartcontractkit/.github/actions/dependency-review@dependency-review/v2
        with:
          config-preset: vulnerability-high
