name: GHA Workflow Validation

on:
  pull_request:
  merge_group:

jobs:
  validate-workflows:
    name: Validate Workflow Changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    # Skip on merge group events
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Run gha-workflow-validator action
        uses: smartcontractkit/.github/actions/gha-workflow-validator@gha-workflow-validator/0.5.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
