###
# This workflow nudges users to mark their pull requests as draft if they are not ready for review.
#
# To disable the comment, set the `PR_DRAFT_NUDGE_COMMENT_DISABLE` variable in the repository settings to `true`.
# The default value is `false`, which means the comment will be posted.
# To set the variable, you can use the GitHub CLI:
#   gh variable set PR_DRAFT_NUDGE_COMMENT_DISABLE --body "true"
###

name: PR Draft Nudge

on:
  pull_request:
    types: [opened]

permissions: {}

env:
  PATH_TO_REPO_SELF: gha-org-workflows

jobs:
  pr-draft-nudge:
    name: PR Draft Nudge
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout org workflows
        uses: actions/checkout@v4
        with:
          repository: smartcontractkit/${{ env.PATH_TO_REPO_SELF}}
          path: ${{ env.PATH_TO_REPO_SELF}}
          persist-credentials: false

      - name: Run
        uses: actions/github-script@v7
        env:
          PR_DRAFT_NUDGE_COMMENT_DISABLE: ${{ vars.PR_DRAFT_NUDGE_COMMENT_DISABLE || 'false' }}
        with:
          script: |
            const pathToRepoSelf = process.env.PATH_TO_REPO_SELF || 'gha-org-workflows';
            const script = require(`./${pathToRepoSelf}/.github/scripts/pr-draft-nudge.js`);
            await script({ github, context, core });
